export const ROUTES = {
  register: '/api/auth/signup',
  signin: '/api/auth/signin',
  renew: '/api/auth/renew',
  sso: '/api/auth/sso',
  ssoCallback: '/api/auth/sso/callback',
  authorization: '/api/auth/authorization',
  auth: '/api/auth/{proxy+}',
  todo: '/api/todo',
  shopifyProxy: '/api/shopify/{proxy+}',
  shopify: '/api/shopify',
  profile: '/api/profile',
  task: '/api/task',
  resetPassword: '/api/reset-password',
  crawler: '/api/crawler',
  telegram: '/api/telegram/{proxy+}',
  telegramWebhook: '/api/telegram/webhook',
};
